### ISSUE TITLE
Nuxt support

### ISSUE THREAD

**Issue by JoshuaPerk** [lorisleiva/solana-wallets-vue#1]
Hi, Loris! Thank you for taking over this package. Has anyone successfully seen this implemented in Nuxt (either 3 or 4)? I'll do my best to document any success I have here for others who might be struggling as I am.

**Comment by JoshuaPerk** [comment]
Still haven't figured it out, but in the spirit of documenting/troubleshooting, here's what I've tried

Install Nuxt plugin in similar fashion to the instructions in this repo:
```js
// plugins/wallet.js
import Vue from 'vue'
import SolanaWallets from 'solana-wallets-vue';

// You can either import the default styles or create your own.
import 'solana-wallets-vue/styles.css';

import {
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
} from '@solana/wallet-adapter-wallets';

const walletOptions = {
  wallets: [
    new PhantomWalletAdapter(),
    new SlopeWalletAdapter(),
    new SolflareWalletAdapter({ network: 'devnet' }),
  ],
  autoConnect: true,
}

Vue.use(SolanaWallets, walletOptions)
```
Globally register the plugin:
```js
// nuxt.config.js
...
  plugins: [{
    src: '~/plugins/wallet.js',
    mode: 'client'
  }]
...
```
Transpile and convert the package to work with Nuxt 3 (Vue 2)
```js
build: {
    transpile: [
      '@solana/wallet-adapter-wallets',
      'solana-wallets-vue'
    ],
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
  }
```
I think I'm _somewhat_ close but may have run into an insurmountable problem as the warnings I'm getting in the console during build and the TypeError I get when Nuxt renders `t.defineComponent is not a function` appear to be errors that populate when a package is reliant on Vue 3.
```
 WARN  in ./node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js                                                         friendly-errors 00:13:05

"export 'toRefs' was not found in 'vue'                                                                                           friendly-errors 00:13:05
                                                                                                                                  friendly-errors 00:13:05

 WARN  in ./node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js                                                         friendly-errors 00:13:05

"export 'unref' was not found in 'vue'                                                                                            friendly-errors 00:13:05
                                                                                                                                  friendly-errors 00:13:05

 WARN  in ./node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js                                                         friendly-errors 00:13:05

"export 'watch' was not found in 'vue'                                                                                            friendly-errors 00:13:05
                                                                                                                                  friendly-errors 00:13:05

 WARN  in ./node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js                                                         friendly-errors 00:13:05

"export 'watchEffect' was not found in 'vue'                                                                                      friendly-errors 00:13:05
                                                                                                                                  friendly-errors 00:13:05

 WARN  in ./node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js                                                         friendly-errors 00:13:05

"export 'withCtx' was not found in 'vue'                                                                                          friendly-errors 00:13:05
                                                                                                                                  friendly-errors 00:13:05

 WARN  in ./node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js                                                         friendly-errors 00:13:05

"export 'withModifiers' was not found in 'vue'  
```

**Comment by lorisleiva** [comment]
Hi Joshua 👋

Thank you for raising this and for explaining your steps so thoroughly!

I think the reason you might get these warnings is that this package uses [`vue-demi`](https://github.com/vueuse/vue-demi) to support both Vue 2 and Vue 3 at the same time. It does that by delegating to the official `@vue/composition-api` package when using Vue 2.

Do you have `@vue/composition-api` in your dependencies? If not, could you try it and let me know if that fixes things?

I'll do some more tests today with both Vue 2 and Vue 3 using different bundlers and frameworks to see if everything works properly. I'll also update the docs to make it easier for people to get started using Vue 2.

**Comment by lorisleiva** [comment]
Okay, I've spent the last 3h trying to debug this and it turns out Vue Demi doesn't work nicely with component templates. Bear with me as I try and find a solution to this. I might need to convert the components into render functions. 🤔

**Comment by JoshuaPerk** [comment]
> Okay, I've spent the last 3h trying to debug this and it turns out Vue Demi doesn't work nicely with component templates. Bear with me as I try and find a solution to this. I might need to convert the components into render functions. 🤔

Thank you for putting so much effort into it — way more than I expected or deserve! From my attempts, I think you're right in narrowing it down to the render functions. That _might_ be a little over my head but I'll continue to try to troubleshoot as well. 🙏🏼

**Comment by lorisleiva** [comment]
Thanks for your message. 🙂

I've continued to debug this and I've refactored all components into render functions but still no success. I've tried different ways of writing the render functions to increase the compatibility and I've even created new helper methods that adjust the behaviour based on using Vue 2 and Vue 3 when rendering. I've released the latest changes as `0.2.0-alpha.7`.

I feel a bit defeated tbh. I took the day off to really try to nail this issue and it's frustrating that I wasn't able to solve it. Vue 3 still works well with the render functions but Vue 2 won't properly call nested components.

I'm going to sleep on it but I think at this point I'm ready to drop support for Vue 2 on this package. Maybe create another package just for Vue 2 until it gets deprecated or something. May I ask what is your use case for using Vue 2 over Vue 3? Is it because Nuxt is not ready on Vue 3 yet?

**Comment by JoshuaPerk** [comment]
That's incredibly frustrating but your effort has been Herculean (I've been following along with your commits).

You're spot on: Nuxt's stable release uses Vue 2 but they recently put a strong beta out that uses Vue 3 so it might not be the worse idea in the world to drop Vue 2 support.

I'm going to see how painful the migration to Nuxt 3 is today.

Thank you, again, for tons and tons of effort on this.

**Comment by JoshuaPerk** [comment]
Tried switching to both Nuxt 3 and Vite + Vue 3 and both worked seamlessly with this repo. 👏🏼 Lovely work!

**Comment by lorisleiva** [comment]
@JoshuaPerk Thank you so much for your help and your moral support haha. I've decided to drop support for Vue 2 in the end. I think even if lots of developers reach out to me asking for Vue 2 support it might make more sense to have a dedicated package for it. I didn't really like all the hacks I had to go through to make it work with Vue Demi and I can imagine it would have been a pain to maintain. Thanks again! 🍺

**Comment by qrtp** [comment]
@JoshuaPerk do you have any advice for upgrading from NuxtJS 2 --> 3? Also is your repo public where you have the wallet adapter working, would love to take a look since I'm pretty new to NuxtJS in general. Thank you!

**Comment by JoshuaPerk** [comment]
Hey, @qrtp! Down the street from you in Holly Springs. How far along is your Nuxt 2 project? I had **tons** of issues using the Nuxt Bridge and ultimately ended up spinning up a brand new Nuxt 3 project and manually migrating everything over. The HTML/CSS will copy over 100% and then there's a few syntax things that change in the JS (particularly `<script setup>` but it's mostly optional).

My repo isn't public as I'm working on an NFT project (who isn't these days 😂 ) but this repo plugged into it really easily since it's just a standard Vue 3 plugin now.

**Comment by tiagoappetite** [comment]
How have you got this working on Nuxt 3?
Installing this as plugin into Nuxt 3 beta I get an error ("ReferenceError: global is not defined")

Tried add vite global on nuxt.config.ts but then app crashes

`vite: {
       define: {
                global: {}
      }
}`

**Comment by tiagoappetite** [comment]
How have you got this working on Nuxt 3? @qrtp @JoshuaPerk 
Installing this as plugin into Nuxt 3 beta I get an error ("ReferenceError: global is not defined")

Tried add vite global on nuxt.config.ts but then app crashes

`vite: { define: { global: {} } }`

**Comment by rhrn** [comment]
### Nuxt3
`src/plugins/solana-wallets-vue.ts`
```
import 'solana-wallets-vue/styles.css'
import SolanaWallets from 'solana-wallets-vue'
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base'
import {
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
} from '@solana/wallet-adapter-wallets'

const walletOptions = {
  wallets: [
    new PhantomWalletAdapter(),
    new SlopeWalletAdapter(),
    new SolflareWalletAdapter({ network: WalletAdapterNetwork.Devnet }),
  ],
  autoConnect: true,
}

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(SolanaWallets, walletOptions)
})
```

`src/components/Wallet.vue`
```
<template>
  <ClientOnly>
    <WalletMultiButton></WalletMultiButton>
  </ClientOnly>
</template>

<script lang='ts' setup>
import { WalletMultiButton } from 'solana-wallets-vue'
</script>
```

**Comment by andysay** [comment]
'/_nuxt/node_modules/bs58/index.js?v=31e31060' does not provide an export named 'default' ... rc-6 nuxt3. problems.

**Comment by boostie** [comment]
I am still getting issues with Nuxt 3, node 16.x and 18.x for including the repo as plugin the same way as the last message. It reads in console: 

`[ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:20:
      4466 │     const U64_MAX = 2n ** 64n - 1n;
           ╵                     ~~

✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:26:
      4466 │     const U64_MAX = 2n ** 64n - 1n;
           ╵                           ~~~

✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:32:
      4466 │     const U64_MAX = 2n ** 64n - 1n;`

I have tried multiple settings for build, but they all give the same result. Anyone having the issue?

**Comment by boostie** [comment]
> I am still getting issues with Nuxt 3, node 16.x and 18.x for including the repo as plugin the same way as the last message. It reads in console:
> 
> `[ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
> 
> ```
> node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:20:
>   4466 │     const U64_MAX = 2n ** 64n - 1n;
>        ╵                     ~~
> ```
> 
> ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
> 
> ```
> node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:26:
>   4466 │     const U64_MAX = 2n ** 64n - 1n;
>        ╵                           ~~~
> ```
> 
> ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
> 
> ```
> node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:32:
>   4466 │     const U64_MAX = 2n ** 64n - 1n;`
> ```
> 
> I have tried multiple settings for build, but they all give the same result. Anyone having the issue?

If I transpile in config like this 

```
build: {
    transpile: [
      "@solana/buffer-layout",
      "@solana/wallet-adapter-base",
      "@solana/wallet-adapter-bitkeep",
      "@solana/wallet-adapter-bitpie",
      "@solana/wallet-adapter-blocto",
      "@solana/wallet-adapter-clover",
      "@solana/wallet-adapter-coin98",
      "@solana/wallet-adapter-coinhub",
      "@solana/wallet-adapter-ledger",
      "@solana/wallet-adapter-mathwallet",
      "@solana/wallet-adapter-phantom",
      "@solana/wallet-adapter-safepal",
      "@solana/wallet-adapter-slope",
      "@solana/wallet-adapter-solflare",
      "@solana/wallet-adapter-sollet",
      "@solana/wallet-adapter-solong",
      "@solana/wallet-adapter-torus",
      "@solana/wallet-adapter-vue",
      "@solana/wallet-adapter-vue-ui",
      "@solana/wallet-adapter-walletconnect",
      "@solana/wallet-adapter-wallets",
      "@solana/web3.js"
    ]
  }
```

The Big Integer error disappears, but this prevents the whole app from loading. Anyone experienced the same thing? 

 `WARN  Sourcemap for "/Users/Shared/data/projects/audacious/audacious-app/node_modules/@solana/buffer-layout/lib/Layout.js" points to missing source files`

Thanks
