### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by JamieBunyassi** [lorisleiva/solana-wallets-vue#11]
Uncaught TypeError: Object(...) is not a function logged when importing solana wallets vue
`
import { useWallet } from 'solana-wallets-vue'

 `

**Comment by lorisleiva** [comment]
Hey there 👋  Can you please open a new issue with more details as to reproduce the error? Ideally with a link to a new public repository that reproduces the issues with minimum configuration needed.

**Comment by JamieBunyassi** [comment]
Solved when upgrading to vue3
