### ISSUE TITLE
Vue2 Support?

### ISSUE THREAD

**Issue by GhoSTBG** [lorisleiva/solana-wallets-vue#12]
Hello,
Im using this package for Vue2 Application. Noticed that it's only Vue3, but I'm using 0.2.0-alpha.7 version, but the Wallet Multi Button isn't showing up. Everything during the setup runs smooth, but that's the first issue I met. There is no way to migrate all my code to Vue3 right now, because I used Vuetify for UI Framework and it's coming out in May. Can you help me solve this issue or continue support for Vue2 as well?

**Comment by lorisleiva** [comment]
Hi there 👋 No sorry support for Vue 2 has been dropped: See https://github.com/lorisleiva/solana-wallets-vue/pull/4
