### ISSUE TITLE
"Wallet not initialized" error

### ISSUE THREAD

**Issue by UdjinnSlutiak** [lorisleiva/solana-wallets-vue#2]
Hello. I'm using your packages, following all instructions, but have this error: "Wallet not initialized. Please use the WalletProvider component to initialize the wallet.". In your example i don't see using of this component, so i'm a little confused about this. Am i doing something wrong, or is this about packages issue?

main.js:

```js
import SolanaWallets from "solana-wallets-vue";
import "solana-wallets-vue/styles.css";
import { PhantomWalletAdapter, SlopeWalletAdapter, SolflareWalletAdapter } from "@solana/wallet-adapter-wallets";

const walletOptions = {
    wallets: [
        new PhantomWalletAdapter(),
        new SlopeWalletAdapter(),
        new SolflareWalletAdapter({ network: "devnet" }),
    ],
    autoConnect: true,
}

const app = createApp(App);

app.use(SolanaWallets, walletOptions);

app.mount("#app");
```

App.vue:

```vue
<script setup>
import { WalletMultiButton } from "@solana/wallet-adapter-vue-ui";
</script>

<template>
    <wallet-multi-button></wallet-multi-button>
</template>
```

**Comment by lorisleiva** [comment]
Hi there 👋

Thanks for raising this.

Which bundler and which version of Vue are you using?

**Comment by UdjinnSlutiak** [comment]
Thank you for answering)

These packages are related to your question:
"@solana/wallet-adapter-base": "^0.9.3",
"@solana/wallet-adapter-vue": "^0.4.5",
"@solana/wallet-adapter-vue-ui": "^0.2.4",
"@solana/wallet-adapter-wallets": "^0.15.3",
"@solana/web3.js": "^1.33.0",
"core-js": "^3.6.5",
"solana-wallets-vue": "^0.1.8",
"vue": "^3.2.29"

I'm using yarn in my project, but your packages I've installed using npm.

**Comment by lorisleiva** [comment]
First of all you should be able to remove the following:

```
"@solana/wallet-adapter-base": "^0.9.3",
"@solana/wallet-adapter-vue": "^0.4.5",
"@solana/wallet-adapter-vue-ui": "^0.2.4",
```

By bundler I mean how do you compile your application? Are you using Vite, Vue CLI, Webpack?

**Comment by UdjinnSlutiak** [comment]
Understood, I'm using Vue CLI 4.5

**Comment by lorisleiva** [comment]
Okay thanks, I checked Vue CLI 5.0 (RC2) today in order to use Webpack 5 but haven't checked Vue CLI 4 yet. I'll try them all soon to see what's going on. At the moment I've still trying to make it work with Vue 2 using Vue Demi. It's been a tough day.

**Comment by JoshuaPerk** [comment]
@UdjinnSlutiak I tried rebuilding your environment and had no issues deploying the component. Do you have an example repo I can clone to try to help you troubleshoot?

**Comment by UdjinnSlutiak** [comment]
@JoshuaPerk Hi. This repo is private, so I can not((
I didn't notice that in my code I was using
`import { WalletMultiButton } from "@solana/wallet-adapter-vue-ui";`
instead of
`import { WalletMultiButton } from "solana-wallets-vue";`

So I replaced it to use "solana-wallets-vue" version. And now i have another error:
`"currentRenderingInstance is null"`

**Comment by lorisleiva** [comment]
@UdjinnSlutiak Would you be able to reproduce the issue in a brand new app and give us the link to the repo?

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Yes, I've just created new repo, here is the link: https://github.com/UdjinnSlutiak/solana-wallets-test-app.git

It didn't help, error still appears.

**Comment by lorisleiva** [comment]
@UdjinnSlutiak Thanks for that! I've just cloned the repo and tested it locally and it all works fine for me. Do you still get the same error with that repo? 🤔

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Yep, "currentRenderingInstance is null" still appears...

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Maybe that's because I have no any wallet extension in my browser??

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Ran code in Google Chrome and had this error:

```
Uncaught TypeError: Cannot read properties of null (reading 'isCE')
renderSlot @ /Users/username/Projects/solana-wallets-test-app/node_modules/solana-wallets-vue/dist/solana-wallets-vue.es.js:1793
```

**Comment by lorisleiva** [comment]
@UdjinnSlutiak Okay so I've added `dedupe: ['vue']` in the Vite config based on [this issue](https://github.com/vuejs/core/issues/4344) and tagged version `0.3.1`. Could you let me know if that solves the issue? I tried on my side but it was also working before so I'm not sure if that made a difference haha.

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Okay, thank you, I will try right now :)

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Unfortunately, it didn't help.
You said that it might be because of Vue CLI... I'm out of ideas why this happens.
Anyway, thank you for your support and answering :)

**Comment by lorisleiva** [comment]
Oh, that's strange. I've been testing it using the same Vue CLI version as you. Maybe it could be an NPM version thing? I'm using node `v16.13.2`. What are you using?

**Comment by UdjinnSlutiak** [comment]
I'm using 8.1.0... Difference is huge...

**Comment by lorisleiva** [comment]
@UdjinnSlutiak No that should be your `npm` version haha mine is `8.1.2`. To get your node version you can run `node -v`. Based on your npm version you should be on node 16 as well.

**Comment by UdjinnSlutiak** [comment]
Sorry, i didn't read question correctly haha.
My node version is `v16.13.0`

**Comment by UdjinnSlutiak** [comment]
If I understood correctly, <a href="https://lorisleiva.com/create-a-solana-dapp-from-scratch/integrating-with-solana-wallets">this is</a> your old guide. Tried it in the same repo and the same error appears...

**Comment by lorisleiva** [comment]
@UdjinnSlutiak It is but it's out-of-date now. I'll update the entire article series to use the new packages soon but that will basically look like the readme of the repo.

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Got it.

**Comment by UdjinnSlutiak** [comment]
@lorisleiva Maybe it will help - the whole debug stack:

```
{isVue3: true}
Using globalProperties
[Vue warn]: Unhandled error during execution of render function

 at <Anonymous>

 at <App>
```

**Comment by lorisleiva** [comment]
```
{isVue3: true}
Using globalProperties
```

This is some `console.log` from an old version. Are you sure you are using the latest version? Try removing your lock file and your node_modules folder and compile everything again. :)

**Comment by lorisleiva** [comment]
@UdjinnSlutiak No worries, I'm glad we got there in the end haha. Have a nice day. 🍺

**Comment by lorisleiva** [comment]
Hi @karnie6 

I've cloned your repo, installed dependencies and used the `.use(SolanaWallets, walletOptions)` without any issue.

The compilation issue you got was likely due to this type that you didn't include in TS.

```ts
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base"
new SolflareWalletAdapter({ network: WalletAdapterNetwork.Devnet }),
```

**Comment by karnie6** [comment]
ok @lorisleiva - i did some digging.  after i matched all the versions of eslint/etc from my test package to the test repo, this appears to work now.  I'll keep you posted if it starts acting up :). Thanks!
