### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by JonDelWeb** [lorisleiva/solana-wallets-vue#26]
Hi ! 

I try to install your package in a vue projet but I got this error with the following command : 

Step to reproduce : 

`npm install solana-wallets-vue @solana/wallet-adapter-wallets`

And the error : 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: daotool@0.1.0
npm ERR! Found: @solana/wallet-adapter-wallets@0.16.10
npm ERR! node_modules/@solana/wallet-adapter-wallets
npm ERR!   @solana/wallet-adapter-wallets@"^0.16.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @solana/wallet-adapter-wallets@"^0.15 | ^0.16" from solana-wallets-vue@0.4.2
npm ERR! node_modules/solana-wallets-vue
npm ERR!   solana-wallets-vue@"*" from the root project
`
Here my package.json : 

` "dependencies": {
    "@solana/wallet-adapter-wallets": "^0.16.10",
    "axios": "^0.27.2",
    "core-js": "^3.8.3",
    "dotenv": "^16.0.1",
    "jquery": "^3.6.0",
    "popper.js": "^1.16.1",
    "vee-validate": "^4.6.2",
    "vue": "^3.2.13",
    "vue-moment": "^4.1.0",
    "vue-router": "^4.0.3",
    "vue-spinner": "^1.0.4",
    "vue3-marquee": "^3.0.7",
    "vuex": "^4.0.0",
    "yup": "^0.32.11"
  },`

I tried to install the solana/wallet-adapter-wallets separatly but also the same issue when I try to install yours... 

Thanks

**Comment by JonDelWeb** [comment]
Seems the last version of @solana/wallet-adapter-wallets is 0.17.1 and your packqage requiers the 0.15 or 0.16 version. 

The last version was pushed there are 6 days ago...

**Comment by lorisleiva** [comment]
Hey there 👋 

I've released a new patch version (`v0.4.3`) that aims to fix this.

Would you mind letting me know if that works for you now? 🍀

**Comment by JonDelWeb** [comment]
Great!  

The installation went well. Not used the packqage yet.

 I'll get back to you as soon as it's done. I close the issue.

Thanks again
