### ISSUE TITLE
Unable to use signMessage

### ISSUE THREAD

**Issue by beargrilo** [lorisleiva/solana-wallets-vue#45]
Hi,

in any wallet I connect (phantom, slope, solflare), I'm unable to `signMessage`.

```js
...
const message = 'A nice message'
const { signMessage } = useWallet()
const signature = await signMessage(message)
...
```

Error:

`app.js:35644 Uncaught (in promise) TypeError: signMessage is not a function`

What am I doing wrong?

**Comment by roguzh** [comment]
Could you solve the issue? I am running into same thing.

**Comment by roguzh** [comment]
```
if (wallet.publicKey.value && wallet.signMessage.value) {
  const encodedMessage = new TextEncoder().encode("Message content");
  const signatureBuffer = await wallet.signMessage.value(encodedMessage);
  const signature = bs58.encode(signatureBuffer);
  console.log(`Public Key: ${wallet.publicKey}\nSignature: ${signature}`);
}
```

That's what I use. I guess depending on the wallet, it may not have signMessage implementation.

**Comment by beargrilo** [comment]
Will give it a try, ty.

**Comment by lorisleiva** [comment]
Hi there, `signMessage` is a computed property and therefore needs to be accessed via `.value`.
