### ISSUE TITLE
Small UX issue

### ISSUE THREAD

**Issue by karnie6** [lorisleiva/solana-wallets-vue#7]
One thing I've been seeing is that whenever you connect your wallet, the dropdown is opened (to copy your address/change your addy/disconnect). Not sure if there's a snafu with the click event, but this is less than ideal UX.

You can see this behavior by playing with my app here: https://gmneedhelp-git-walletux-gmnhlabs.vercel.app/

**Comment by lorisleiva** [comment]
Hey, thanks for raising this. Yeah, I noticed that too. It only happens if you're reconnecting a wallet that's already been connected before. There's must be an event somewhere that needs a `stopPropagation` or a `preventDefault`.

**Comment by lorisleiva** [comment]
This should be fixed now.
