### ISSUE TITLE
Error with nuxtjs

### ISSUE THREAD

**Issue by qrtp** [lorisleiva/solana-wallets-vue#9]
Hi, I'm trying to use instructions for the wallet adapter in NuxtJS.

in the `plugins` directory I have `wallet.js` like this:

```
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
import {
    PhantomWalletAdapter,
    SlopeWalletAdapter,
    SolflareWalletAdapter
} from '@solana/wallet-adapter-wallets';
import SolanaWallets from 'solana-wallets-vue';
import 'solana-wallets-vue/styles.css';
import Vue from 'vue';

const walletOptions = {
    wallets: [
        new PhantomWalletAdapter(),
        new SlopeWalletAdapter(),
        new SolflareWalletAdapter({ network: WalletAdapterNetwork.Devnet }),
    ],
    autoConnect: true,
}

Vue.use(SolanaWallets, walletOptions)
```

At runtime in the browser, I'm getting this error. I'm pretty new to Vue and NuxtJS in general, so I'm likely missing something simple. Do you have any guidance? Thanks so much!

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/21039114/154667072-715344fd-401e-4eaa-8907-f55b06c2575e.png">

**Comment by lorisleiva** [comment]
Hi there 👋 Which version of NuxtJs are you using? This package only works with Vue 3.

**Comment by qrtp** [comment]
Thanks, this helps a lot. Here's what I see:

```
=> Found "nuxt@2.15.8"
```

And with Vue developer tools seeing
<img width="420" alt="image" src="https://user-images.githubusercontent.com/21039114/154671743-a240abfd-6c52-478a-8dc3-6fd814b43fb2.png">

I'll attempt to upgrade both NuxtJS and Vue and see what happens. Anything you would suggest for me to watch out for?

**Comment by lorisleiva** [comment]
No worries. Someone else successfully used this package with Vue 3 and NuxtJS 3 so I think you'll be fine. 🙂
